site_name: ERCOT Developer Portal
repo_name: aahmad-ercot/ERCOT_DEVPORTAL
repo_url: https://github.com/aahmad-ercot/ERCOT_DEVPORTAL

theme:
  name: material
  logo: assets/ercot-logo-white.svg
  custom_dir: overrides
  features:
  - announce.dismiss
  # - content.action.edit
  # - content.action.view
  #- content.code.annotate
  # - content.code.copy
  # - content.code.select
  # - content.tabs.link
  - content.tooltips
  - header.autohide
  # - navigation.expand
  #- navigation.footer
  #- navigation.indexes
  # - navigation.instant.prefetch
  # - navigation.instant.progress
  # - navigation.prune
  - navigation.sections
  # - navigation.instant
  - navigation.tabs
  - navigation.top
  # - navigation.tabs.sticky
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  icon:
    logo: logo
  palette:
  - scheme: default
    primary: white
    accent: cyan
    toggle:
      icon: material/lightbulb
      name: Light/Dark Mode Toggle
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Light/Dark Mode Toggle

nav:
- Home: index.md
- Applications:
  - ERCOT Web Services: applications/ews/ews.md
  - Marketrak: applications/marketrak/marketrak.md
  - Public API: applications/pubapi/pubapi.md
- API Sites:
  - ERCOT Web Services: api_sites/ews/ews.md
  - Marketrak API: api_sites/marketrak/marketrak.md
  - Public API: api_sites/pubapi/pubapi.md
  - Retail API: api_sites/retail/retail.md
- Discussion Forum: discussion_forum/forum.md
- Support: support/support.md

# Plugins
plugins:
- blog
- search:
    separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
- git-revision-date-localized:
    enable_creation_date: false
    fallback_to_build_date: true
# - git-committers:
#     repository: https://github.com/aahmad-ercot/ERCOT_DEVPORTAL
#     branch: main

extra:
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
  - icon: fontawesome/brands/facebook
    link: http://facebook.com
  - icon: fontawesome/brands/twitter
    link: http://twitter.com
  - icon: fontawesome/brands/linkedin
    link: http://linkedin.com
  - icon: fontawesome/brands/youtube
    link: http://youtube.com


markdown_extensions:
- neoteroi.cards

extra_css:
- css/neoteroi-mkdocs.css
- css/custom.css
- stylesheets/extra.css

copyright: Copyright &copy; 1996-2024 Electric Reliability Council of Texas, Inc. All rights reserved.
